on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5.0.0
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: ${{ github.ref_name == 'dev' && 'release-please-config-dev.json' || 'release-please-config.json' }}
          manifest-file: ${{ github.ref_name == 'dev' && '.release-please-manifest-dev.json' || '.release-please-manifest.json' }}
          target-branch: ${{ github.ref_name }}